# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Visualization and PDF export tools"""

from google.adk.tools import FunctionTool
from ..utils import plot_stock_trend, generate_pdf_report


def _create_stock_trend_plot(market_analysis: str) -> str:
    """
    Create a stock price trend visualization chart from market analysis data.

    This tool generates a 30-day price trend chart showing the stock's recent
    performance, including trend direction (uptrend, downtrend, or sideways).

    Args:
        market_analysis: The market analysis output containing stock price data,
                        trend information, and ticker symbol

    Returns:
        str: Path to the saved chart image file (saved in Downloads folder)
    """
    try:
        file_path = plot_stock_trend(market_analysis)
        return f"Stock trend chart created successfully! Saved to: {file_path}"
    except Exception as e:
        return f"Error creating stock trend chart: {str(e)}"


def _export_summary_to_pdf(summary_text: str, ticker: str) -> str:
    """
    Export the executive summary to a formatted PDF report.

    This tool takes the executive summary generated by the summary_agent and
    creates a professional PDF document saved to the Downloads folder.

    Args:
        summary_text: The executive summary text from the summary_agent
        ticker: The stock ticker symbol (e.g., "AAPL", "GOOGL")

    Returns:
        str: Path to the saved PDF file
    """
    try:
        file_path = generate_pdf_report(summary_text, ticker)
        return f"PDF report created successfully! Saved to: {file_path}\n\nYou can now download and review the complete financial analysis report.\n\nReminder: This entire process is for EDUCATIONAL and INFORMATIONAL purposes ONLY and does NOT constitute financial advice. All investment decisions should be made after conducting your own thorough research and, ideally, consulting with a qualified independent financial advisor."
    except Exception as e:
        return f"Error creating PDF report: {str(e)}"


# Create FunctionTool instances
create_stock_trend_plot = FunctionTool(func=_create_stock_trend_plot)
export_summary_to_pdf = FunctionTool(func=_export_summary_to_pdf)
