# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""PDF report generator for financial analysis"""

import os
from datetime import datetime
from fpdf import FPDF


class FinancialReportPDF(FPDF):
    """Custom PDF class for financial reports"""

    def header(self):
        """Add header to each page"""
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'Financial Advisory Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        """Add footer to each page"""
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title):
        """Add chapter title"""
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(220, 220, 220)
        self.cell(0, 8, title, 0, 1, 'L', True)
        self.ln(2)

    def section_title(self, title):
        """Add section title"""
        self.set_font('Arial', 'B', 10)
        self.cell(0, 6, title, 0, 1, 'L')
        self.ln(1)

    def body_text(self, text):
        """Add body text"""
        self.set_font('Arial', '', 9)
        self.multi_cell(0, 5, text)
        self.ln(2)

    def add_separator(self):
        """Add horizontal separator line"""
        self.ln(2)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)


def generate_pdf_report(summary_text: str, ticker: str = "STOCK") -> str:
    """
    Generate PDF report from executive summary text

    Args:
        summary_text: The executive summary text from summary_agent
        ticker: The stock ticker symbol

    Returns:
        str: Path to the generated PDF file
    """
    # Clean special characters that aren't supported by default PDF fonts
    def clean_text_for_pdf(text: str) -> str:
        """Replace unsupported characters with PDF-safe alternatives"""
        replacements = {
            '•': '-',           # Bullet point
            '–': '-',           # En dash
            '—': '-',           # Em dash
            ''': "'",           # Smart single quote
            ''': "'",           # Smart single quote
            '"': '"',           # Smart double quote
            '"': '"',           # Smart double quote
            '…': '...',         # Ellipsis
            '→': '->',          # Right arrow
            '←': '<-',          # Left arrow
            '✓': '[X]',         # Check mark
            '✅': '[OK]',       # Check mark emoji
            '❌': '[X]',        # Cross mark
            '⚠️': '[!]',        # Warning
            '📊': '[Chart]',    # Chart emoji
            '📈': '[Up]',       # Trending up
            '📉': '[Down]',     # Trending down
            '💰': '[$]',        # Money bag
            '⏰': '[Time]',     # Clock
        }

        for char, replacement in replacements.items():
            text = text.replace(char, replacement)

        # Remove any remaining non-ASCII characters
        text = text.encode('ascii', 'ignore').decode('ascii')

        return text

    # Clean the summary text before processing
    summary_text = clean_text_for_pdf(summary_text)

    pdf = FinancialReportPDF()
    pdf.add_page()

    # Title page
    pdf.set_font('Arial', 'B', 20)
    pdf.ln(20)
    pdf.cell(0, 10, 'FINANCIAL ADVISORY', 0, 1, 'C')
    pdf.cell(0, 10, 'EXECUTIVE SUMMARY', 0, 1, 'C')
    pdf.ln(10)

    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, f'Ticker: {ticker.upper()}', 0, 1, 'C')
    pdf.cell(0, 8, f'Report Date: {datetime.now().strftime("%B %d, %Y")}', 0, 1, 'C')
    pdf.ln(10)

    pdf.set_font('Arial', 'I', 10)
    pdf.multi_cell(0, 6, 'Generated by AI Financial Advisory System', 0, 'C')

    # Add new page for content
    pdf.add_page()

    # Parse and format the summary text
    lines = summary_text.split('\n')

    for line in lines:
        line = line.strip()

        # Clean each line for PDF-safe characters
        line = clean_text_for_pdf(line)

        if not line:
            pdf.ln(2)
            continue

        # Handle section headers (lines with ═══)
        if '═══' in line:
            continue

        # Handle main section titles (1., 2., 3., etc.)
        if line and line[0].isdigit() and '.' in line[:3]:
            pdf.add_separator()
            pdf.chapter_title(line)

        # Handle subsection titles (** at start)
        elif line.startswith('**'):
            clean_line = line.replace('**', '').strip()
            if clean_line:
                pdf.section_title(clean_line)

        # Handle bullet points
        elif line.startswith('*') or line.startswith('-'):
            clean_line = line.lstrip('*-').strip()
            if clean_line:
                pdf.set_font('Arial', '', 9)
                pdf.cell(10)  # Indent
                pdf.multi_cell(0, 5, f'• {clean_line}')

        # Handle table-like content (|)
        elif '|' in line and not line.strip().startswith('|'):
            pdf.set_font('Courier', '', 8)
            pdf.cell(0, 5, line, 0, 1)

        # Handle regular text
        else:
            # Check if it's a title (CAPS or contains ":")
            if line.isupper() or ':' in line[:50]:
                pdf.set_font('Arial', 'B', 9)
                pdf.multi_cell(0, 5, line)
            else:
                pdf.set_font('Arial', '', 9)
                pdf.multi_cell(0, 5, line)

        pdf.ln(1)

    # Generate filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"financial_report_{ticker.upper()}_{timestamp}.pdf"

    # Save to downloads directory or current directory
    downloads_dir = os.path.expanduser("~/Downloads")
    if os.path.exists(downloads_dir):
        filepath = os.path.join(downloads_dir, filename)
    else:
        filepath = filename

    pdf.output(filepath)

    return filepath
